### ISSUE TITLE
Add new page slide to http://brigidinetv.powertracker.com.au/

### ISSUE THREAD

**Issue by mjoconnell** [brigidine/brigidinetv.powertracker.com.au#1]
Add this page to the end of the slide with the following amendments

page to add to slide: http://brigidine.powertracker.com.au/leaderboard/

remove header
remove footer
remove full leaderboard button

**Comment by geofftech** [comment]
This is done. 

The data comes from `topleaders.json` on the main site and the data is used to propagate the place holders on the leaders page.

Avatar images are linked directly to the main site.

Also separated out the pages into includes. Separated out the javascript. And moved the CSS into SASS.
